---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cardano-node
spec:
  selector:
    matchLabels:
      app: cardano-node
  serviceName: cardano-node
  replicas: 1
  template:
    metadata:
      labels:
        app: cardano-node
    spec:
      containers:
        - name: cardano-node
          image: inputoutput/cardano-node:1.35.3
          command:
            [
              "cardano-node",
              "run",
              "--config",
              "/config/config.json",
              "--topology",
              "/config/topology.json",
              "--database-path",
              "/storage/cardano-node-db",
            ]
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /storage
              name: cardano-node-storage
      volumes:
        - name: config
          configMap:
            name: cardano-node-config
  volumeClaimTemplates:
    - metadata:
        name: cardano-node-storage
      spec:
        resources:
          requests:
            storage: 80Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
