global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]
  - job_name: grafana
    static_configs:
      - targets: [grafana.default.svc.cluster.local]
  - job_name: cardano-node
    static_configs:
      - targets: [cardano-node.default.svc.cluster.local:12798]
  - job_name: kube-state-metrics
    static_configs:
      - targets: [kube-state-metrics.default.svc.cluster.local:8080]
  - job_name: kubelet
    scheme: https
    kubernetes_sd_configs:
      - role: node
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  - job_name: kubelet-cadvisor
    scheme: https
    kubernetes_sd_configs:
      - role: node
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    metrics_path: /metrics/cadvisor
  - job_name: kubelet-apiserver
    scheme: https
    kubernetes_sd_configs:
      - role: endpoints
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: keep
        regex: default;kubernetes;https
        source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        - __meta_kubernetes_endpoint_port_name
